### ISSUE TITLE
项目问题

### ISSUE THREAD

**Issue by mmyao** [qinyou/my_curd#1]
为什么项目启动编译不过去，报错；怎么在idea中启动jfinal项目？求解

**Comment by mmyao** [comment]
#

- [](url)
![jfinal](https://user-images.githubusercontent.com/31951159/35142847-9ce5e422-fd3a-11e7-878f-4e722ed50fd4.png)

**Comment by mmyao** [comment]
启动就这个错

**Comment by qinyou** [comment]
idea 的 java 编译设置为1.7（好像是默认） 造成的错误。
可以：  Setting  ->  Java Compiler 设置一下 java 编译版本为 1.8
             Project Structure 确保项目jdk版本是1.8
