### ISSUE TITLE
oa包里面好几个类都没了

### ISSUE THREAD

**Issue by yinxinwuzeen** [qinyou/my_curd#2]
Error:(6, 37) java: 找不到符号
  符号:   类 ActivitiUtils
  位置: 程序包 com.github.qinyou.oa.activiti

Error:(22, 35) java: 程序包org.activiti.engine.history不存在

Error:(23, 35) java: 程序包org.activiti.engine.runtime不存在

Error:(15, 28) java: 找不到符号
  符号:   类 OARoute
  位置: 程序包 com.github.qinyou.oa

Error:(18, 37) java: 找不到符号
  符号:   类 ActivitiPlugin
  位置: 程序包 com.github.qinyou.oa.activiti

是没传上来吗？

**Comment by qinyou** [comment]
现在 已经上传了， 但要做好填坑的准备（功能还没做完，代码也比较乱）
这里整合 activiti 使用普通表单（业务表单）也是要写 相当一部分代码的，适合 申请表单 变更 不频繁的 审批功能。后续会写个针对 流程申请 表单 的代码生成器，尽量减少 样板代码工作量。

**Comment by yinxinwuzeen** [comment]
编译成功了，谢谢，启动后OA办公前三个流程404，从权限管理里面的机构盲猜老兄是郑州思念食品里面做内部管理系统的开发人员，公司部门架构是不是暴露了，可以找几个大公司架构当例子感觉比较好一点（小建议哈），写得挺好的，还有个问题是修改后记录的跳转不是很明显，我新增加了一个机构进去，点半天“确定”，后台日志显示已经插入数据了，可是前端页面展示还是那个新增编辑的页面，之前改头像和改管理员信息的时候也是，还有一个编辑过程中不小心点到其他地方就退出的问题，而且记录没有缓存，我上传了三次头像，upload文件夹里面三张图片存储下来，但是编辑那个我录了三次，不小心点错似乎很影响用户体验。
